name: Sync To Gitee
on:
    workflow_call:
    workflow_dispatch:
    # workflow_run:
    #   workflows: ["Sync Fork"] # 指定触发该工作流的上一个工作流名称
    #   types:
    #     - completed
jobs:
  sync:
    runs-on: ubuntu-latest
    environment: GITEE_RSA_KEY

    steps:
      - name: Checkout code  
        uses: actions/checkout@v3  

      - name: sync to gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/musekeeper
          dst: gitee/musekeeper
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}  # SSH密钥对中的私钥
          dst_token:  ${{ secrets.GITEE_TOKEN }}  # Gitee账户的私人令牌
          account_type: user  # 账户类型
          static_list: "MaaResource"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个
          timeout: '600s'  # git超时设置，超时后会自动重试git操作
          force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
          debug: true  # 启用后会显示所有执行命令
