name: Sync Fork

on:  
  schedule:  
    # 东八区下午4-11点（UTC 8-15点）每小时运行  
    - cron: '0 8-15 * * *'  
    # 每天早上 9-11 点（UTC 1-3点）每小时运行  
    - cron: '0 1-3 * * *'  
    # 下午5点30分、6点30分、7点30分（UTC 9:30, 10:30, 11:30）  
    - cron: '30 9,10,11 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: GITEE_RSA_KEY

    steps:
      - name: Checkout code  
        uses: actions/checkout@v3  

        
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main
          # REQUIRED 'target_repo_token' exactly like this!
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: MaaAssistantArknights/MaaResource
      - name: New commits found
        if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "New commits were found to sync."
      
      - name: No new commits
        if: steps.sync.outputs.has_new_commits == 'false'
        uses: ./.github/actions/Sync To Gitee

        # run: echo "There were no new commits."

        
      - name: Show value of 'has_new_commits'
        run: echo ${{ steps.sync.outputs.has_new_commits }}


        # Set test_mode true during manual dispatch to run tests instead of the true action!!
          # test_mode: ${{ inputs.sync_test_mode }}
        
      # - name: sync from upstream
      #   uses: TG908/fork-sync@v1.1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     owner: MaaAssistantArknights
      #     base: main
      #     head: main

      # - name: Async Github Branch To Gitee
      #   uses: shanghaobo/github-branch-gitee@main
      #   with:
      #     github_repo: musekeeper/MaaResource
      #     github_branch: dev
      #     gitee_repo: musekeeper/MaaResource
      #     gitee_branch: main
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}    


      
      # - name: sync-gitee-mirror
      #   uses: abersheeran/sync-gitee-mirror@v1-beta
      #   with:
      #     repository: musekeeper/MaaResource
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}

          
      # - name: sync to gitee
      #   uses: Yikun/hub-mirror-action@master
      #   with:
      #     src: github/musekeeper
      #     dst: gitee/musekeeper
      #     dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}  # SSH密钥对中的私钥
      #     dst_token:  ${{ secrets.GITEE_TOKEN }}  # Gitee账户的私人令牌
      #     account_type: user  # 账户类型
      #     static_list: "MaaResource"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个
      #     timeout: '600s'  # git超时设置，超时后会自动重试git操作
      #     force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
      #     debug: true  # 启用后会显示所有执行命令



