name: Sync Fork And Push To Gitee

on:  
  schedule:  
    # 东八区下午4-11点（UTC 8-15点）每小时运行  
    - cron: '0 8-15 * * *'  
    # 每天早上 9-11 点（UTC 1-3点）每小时运行  
    - cron: '0 1-3 * * *'  
    # 下午5点30分、6点30分、7点30分（UTC 9:30, 10:30, 11:30）  
    - cron: '30 9,10,11 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: GITEE_RSA_KEY

    steps:
      - name: sync from upstream
        uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: MaaAssistantArknights
          base: main
          head: main
      - name: sync to gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/musekeeper
          dst: gitee/musekeeper
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}  # SSH密钥对中的私钥
          dst_token:  ${{ secrets.GITEE_TOKEN }}  # Gitee账户的私人令牌
          account_type: user  # 账户类型
          static_list: "MaaResource"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个
          timeout: '600s'  # git超时设置，超时后会自动重试git操作
          force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
          debug: true  # 启用后会显示所有执行命令



